=== Guiz711/RTV1-RT/xml/def.dtd
<!ELEMENT repertoire (personne*)>

<!ELEMENT personne (nom, prenom, adresse, telephones, emails)>
<!ATTLIST personne sexe (masculin | feminin) #REQUIRED>

<!ELEMENT nom (#PCDATA)>
<!ELEMENT prenom (#PCDATA)>

<!ELEMENT adresse (numero, voie, codePostal, ville, pays)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT voie (#PCDATA)>
<!ATTLIST voie type CDATA #REQUIRED>
<!ELEMENT codePostal (#PCDATA)>
<!ELEMENT ville (#PCDATA)>
<!ELEMENT pays (#PCDATA)>

<!ELEMENT telephones (telephone+)>
<!ELEMENT telephone (#PCDATA)>
<!ATTLIST telephone type CDATA #REQUIRED>

<!ELEMENT emails (email+)>
<!ELEMENT email (#PCDATA)>
<!ATTLIST email type CDATA #REQUIRED>

=== Guiz711/RTV1-RT/xml/xml_test.xml
<?xml version = "1.0" encoding="UTF-8" standalone="no" ?>

<!DOCTYPE repertoire SYSTEM "def.dtd">

<repertoire>
	<!-- Bernard Doe -->
	<personne sexe="masculin">
		<nom>DOE</nom>
		<prenom>Bernard</prenom>
		<adresse>
			<numero>7</numero>
			<voie type="impasse">impasse du chemin</voie>
			<codePostal>75015</codePostal>
			<ville>PARIS</ville>
			<pays>FRANCE</pays>
		</adresse>
		<telephones>
			<telephone type="fixe">01 02 03 04 05</telephone>
			<telephone type="portable">06 07 08 09 10</telephone>
		</telephones>
		<emails>
			<email type="personnel">bernard.doe@wanadoo.fr</email>
			<email type="professionnel">bernard.doe@societe.com</email>
		</emails>
	</personne>>

	<personne sexe="feminin">
		<nom>POPPINS</nom>
		<prenom>Marie</prenom>
		<adresse>
			<numero>28</numero>
			<voie type="avenue">avenue de la r√©publique</voie>
			<codePostal>13005</codePostal>
			<ville>MARSEILLE</ville>
			<pays>FRANCE</pays>
		</adresse>
		<telephones>
			<telephone type="bureau">04 05 06 07 08</telephone>
		</telephones>
		<emails>
			<email type="professionnel">contact@poppins.fr</email>
		</emails>
	</personne>
</repertoire>
